language: node_js
node_js: stable

cache:
    directories:
        - node_modules

before_deploy:
    - 'npm run build:docs'

deploy:
    provider: pages
    github_token: $GITHUB_TOKEN
    local_dir: dist-docs
    on:
        branch: master
